en:
  # you can leave empty locales, for example the default one
it:
  en: it
  sign_in: accesso
  sign_up: registrazione
  sign_out: uscita
  users: utenti
  cancel: annulla
  edit: modifica
  new: nuova